### ISSUE TITLE
Crash after update

### ISSUE THREAD

**Issue by duculete** [mcchots/homebridge-mqtt-temperature#10]
in my case after updating to 6.0 the plugin(s) were crashing...

[6/1/2018, 8:36:55 AM] ERROR LOADING PLUGIN homebridge-mqtt-humidity:
Jun 01 08:36:55 homebridge homebridge[22817]: [6/1/2018, 8:36:55 AM] Error: Cannot find module 'debug'
Jun 01 08:36:55 homebridge homebridge[22817]:     at Function.Module._resolveFilename (module.js:470:15)

after commenting all "debug" it works

**Comment by mcchots** [comment]
Whoops. I did something silly.

Should be fixed in both plugins now.

Reference: 67c0087
